### ISSUE TITLE
How to run evaluate.py

### ISSUE THREAD

**Issue by okisy** [batra-mlp-lab/visdial-rl#2]
Hello.
Thank you for sharing your great work!

After running 
`python evaluate.py -useGPU \
    -startFrom checkpoints/abot_sl_ep60.vd \
    -qstartFrom checkpoints/qbot_sl_ep60.vd \
    -evalMode ABotRank QBotRank>`
, I had lots of the following error
> [Errno110] Connection timed out

I guess before running 
`python evaluate.py -useGPU \
    -startFrom checkpoints/abot_sl_ep60.vd \
    -qstartFrom checkpoints/qbot_sl_ep60.vd \
    -evalMode ABotRank QBotRank`
, I should run 
`python -m visdom.server -p <port>`
in order to visualize the evaluation result.
Is it correct?

If not, how should I deal with this code?

**Comment by nirbhayjm** [comment]
Thanks for pointing this out - currently all evaluations need a visdom server for plotting and displaying results. I have updated the evaluation commands in the README to reflect this in 07725610abac95c6090ba1313de366d85e1441a8.
