### ISSUE TITLE
Somehow -visdomServer is overwritten in an unexpected way

### ISSUE THREAD

**Issue by okisy** [batra-mlp-lab/visdial-rl#3]
This is related to https://github.com/batra-mlp-lab/visdial-rl/issues/2
I ran 
`python -m visdom.server -p 8097`
in order to use visdom.

After that, I ran
`python evaluate.py -useGPU \
    -startFrom checkpoints/abot_sl_ep60.vd \
    -qstartFrom checkpoints/qbot_sl_ep60.vd \
    -evalMode ABotRank QBotRank \
    -visdomServer http://127.0.0.1 \
    -visdomServerPort 8097 \
    -visdomEnv ABotRank-QBotRank`
Even though I clearly designated which server to use and the server port number, somehow they are overwritten as follows. How can I fix this?
>{'CELossCoeff': 200,
 'batchSize': 20,
 'beamSize': 1,
 'ckpt_iterid': 152160,
 'ckpt_lRate': 4.999614155150613e-05,
 'cocoDir': '',
 'cocoInfo': '',
 'continue': True,
 'decoder': 'gen',
 'dropout': 0.0,
 'embedSize': 300,
 'enableVisdom': 1,
 'encoder': 'hre-ques-lateim-hist',
 'evalModeList': ['ABotRank', 'QBotRank'],
 'evalSplit': 'val',
 'evalTitle': 'eval',
 'featLossCoeff': 1000,
 'freezeQFeatNet': 0,
 'imgEmbedSize': 300,
 'imgFeatureSize': 4096,
 'imgNorm': 1,
 'inputImg': 'data/visdial/data_img.h5',
 'inputJson': 'data/visdial/chat_processed_params.json',
 'inputQues': 'data/visdial/chat_processed_data.h5',
 'learningRate': 0.001,
 'lrDecayRate': 0.9997592083,
 'minLRate': 5e-05,
 'numEpochs': 65,
 'numLayers': 2,
 'numRounds': 10,
 'numWorkers': 2,
 'qdecoder': 'gen',
 'qencoder': 'hre-ques-lateim-hist',
 'qstartFrom': 'checkpoints/qbot_sl_ep60.vd',
 'randomSeed': 32,
 'rlAbotReward': 1,
 'rnnHiddenSize': 512,
 'saveName': 'debug-final5_sl-qbot',
 'savePath': 'checkpoints/debug-final5_sl-qbot',
 'startFrom': 'checkpoints/abot_sl_ep60.vd',
 'trainMode': 'sl-abot',
 'useCurriculum': 1,
 'useGPU': True,
 'useHistory': True,
 'useIm': 'late',
 'verbose': 1,
 'visdomEnv': 'ABotRank-QBotRank',
 'visdomServer': 'http://walle.cc.gatech.edu',
 'visdomServerPort': 8893,
 'vocabSize': 7826}

**Comment by nirbhayjm** [comment]
Thanks for pointing this out, the visdom parameters were being overwritten in `evaluate.py` with the ones loaded from checkpoint. I have added those parameters to the list of excluded parameters in 58110e2e542260bd145a28bd480eb8ad6003e3ad to prevent this. Let me know if the issue persists.
